spring:
    application:
        name: persistence
    datasource:
        url: jdbc:p6spy:h2:mem:persistence;DB_CLOSE_ON_EXIT=FALSE;MODE=LEGACY
        username: sa
        password:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    jpa:
        database: H2
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                show_sql: true
